---
- name: Deploy App in docker container
  hosts: dhs
  gather_facts: true

  vars:
    - container_name: reddit
    - container_image: naselin/otus-reddit:1.0

  tasks:
    - name: Add current user to group "docker"
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true

    - name: Reset SSH connection to allow user changes to affect ansible user
      ansible.builtin.meta: reset_connection

    - name: Create app container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        exposed_ports:
          - 9292
        ports:
          - 80:9292
        restart_policy: always
        state: started
