---
- hosts: all
  become: true
  name: Install Docker and its dependent components
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    ansible.builtin.apt:
      state: present
      update_cache: true
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

  - name: Add an apt signing key for Docker
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Install docker and its dependecies
    ansible.builtin.apt:
      state: present
      update_cache: true
      pkg:
        - docker-ce
        - docker-ce-cli
        - docker-compose
        - containerd.io

  - name: Add ubuntu user to docker group
    ansible.builtin.user:
      name: ubuntu
      group: docker
